package com.agentmemorystore.domain.model;

/**
 * Discriminator for memory types stored in the single {@code memories} table.
 *
 * @see com.agentmemorystore.domain.model.Memory
 */
public enum MemoryType {

    /** Created via API — primary type in MVP. */
    EPISODIC,

    /** Generated by the consolidation batch job (episodic → semantic). */
    SEMANTIC,

    /** Defined in schema but not implemented in the MVP. */
    PROCEDURAL
}
